app/info/__init__.py
from flask import Blueprint

info_blueprint = Blueprint('info', __name__, template_folder="templates/info")

from . import views

app/info/views.py
from flask import make_response, redirect, render_template, request, url_for, flash
from flask_login import current_user, login_required
from . import info_blueprint

@info_blueprint.route('/info')
@login_required
def info():
    # if 'name' not in session:
    #     flash('Please log in first!', 'danger')
    #     return redirect(url_for('login'))

    name = current_user.username
    cookies = request.cookies.items()

    return render_template('info.html', name=name, cookies=cookies)

@info_blueprint.route('/delete_all_cookies', methods=['POST'])
def delete_all_cookies():
    flash('All cookies deleted!', 'primary')
    resp = make_response(redirect(url_for('info.info')))

    cookies = request.cookies
    for key in cookies.keys():
        resp.delete_cookie(key)

    return resp

@info_blueprint.route('/add_cookie', methods=['POST'])
def add_cookie():
    key = request.form.get('key')
    value = request.form.get('value')
    expiry = int(request.form.get('expiry'))

    flash('Cookie added!', 'primary')
    resp = make_response(redirect(url_for('info.info')))

    resp.set_cookie(key, value, max_age=expiry)

    return resp

@info_blueprint.route('/delete_cookie', methods=['POST'])
def delete_cookie():
    delete_key = request.form.get('delete_key')

    flash('Cookie deleted!', 'primary')
    resp = make_response(redirect(url_for('info.info')))

    resp.delete_cookie(delete_key)

    return resp

app/info/templates/info/info.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block body %}

<div style="text-align: center; padding: 20px; max-width: 80%;">
    <h1>Welcome to the Info Page, {{ name }}!</h1>
</div>

<div style="max-width: 60%;">
    <div>
        <form method="post" action="{{ url_for('info.add_cookie') }}">
            <div>
                <label for="key">Key</label>
                <input name="key" id="key" placeholder="Enter key" type="text">
            </div>
            <div>
                <label for="value">Value</label>
                <input name="value" id="value" placeholder="Value" type="text">
            </div>
            <div>
                <label for="expiry">Expiry(seconds)</label>
                <input name="expiry" id="expiry" placeholder="Expiry" type="text">
            </div>
            <button type="submit">Submit</button>
        </form>
    </div>
</div>

<div style="max-width: 60%;">
    <div>
        <form method="post" action="{{ url_for('info.delete_cookie') }}">
            <div>
                <label for="delete_key">Delete Cookie by Key</label>
                <input name="delete_key" id="delete_cookie" placeholder="Delete cookie" type="text">
            </div>
            <button type="submit">Delete cookie</button>
        </form>
    </div>
</div>

<div style="max-width: 60%;">
    <div>
        <form method="post" action="{{ url_for('info.delete_all_cookies') }}">
            <button type="submit">Delete all cookies</button>
        </form>
    </div>
</div>

<div style="max-width: 60%;">
    <div>
        <table style="width: 100%; text-align: center;">
            <thead>
                <tr>
                    <th scope="col">Key</th>
                    <th scope="col">Value</th>
                </tr>
            </thead>
            <tbody>
                {% for cookie_key, cookie_value in cookies %}
                    <tr>
                        <td>{{ cookie_key }}</td>
                        <td>{{ cookie_value }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}