app/todo/models.py
from app import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    complete = db.Column(db.Boolean)
    description = db.Column(db.String(250))

app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class TodoForm(FlaskForm):
    title = StringField("Enter a task here", validators=[DataRequired(message="This field is required.")])
    description = StringField("Describe your task", validators=[DataRequired(message="This field is required.")])
    submit = SubmitField("Save")

app/todo/__init__.py
from flask import Blueprint

todo_blueprint = Blueprint('todo', __name__, template_folder="templates/todo")

from . import views

app/todo/views.py
from flask import redirect, render_template, url_for, flash
from .forms import TodoForm
from .models import Todo
from . import todo_blueprint
from app import db

@todo_blueprint.route('/todo', methods=['GET', 'POST'])
def todo():
    form = TodoForm()
    todo_list = Todo.query.all()
    return render_template("todo.html", form=form, todo_list=todo_list)

@todo_blueprint.route('/add', methods=["POST"])
def add():
    form = TodoForm()

    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        new_todo = Todo(title=title, description=description, complete=False)
        db.session.add(new_todo)
        db.session.commit()
        flash('Todo added successfully', 'success')
    else:
        flash('Invalid input. Please try again.', 'danger')

    return redirect(url_for("todo.todo"))

@todo_blueprint.route('/update/<int:todo_id>')
def update(todo_id):
    todo = db.get_or_404(Todo, todo_id)
    todo.complete = not todo.complete
    db.session.commit()
    flash('Todo updated successfully', 'success')
    return redirect(url_for('todo.todo'))

@todo_blueprint.route('/delete/<int:todo_id>')
def delete(todo_id):
    todo = db.get_or_404(Todo, todo_id)
    db.session.delete(todo)
    db.session.commit()
    flash('Todo deleted successfully', 'success')
    return redirect(url_for('todo.todo'))

app/todo/templates/todo/todo.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block title %} To Do{% endblock %}
{% block body %}

<div style="text-align: center; padding-top: 20px;">
    <h1>To Do List</h1>
</div>
<div style="max-width: 60%;">
    <div>
        <form method="post" action="{{ url_for('todo.add') }}" novalidate>
            {{ form.csrf_token }}
            {{ render_field(form.title)}}
            {{ render_field(form.description)}}
            {{ form.submit(class="btn-round btn btn-primary btn-lg") }}
        </form>
    </div>
</div>
<div>
    <table responsive>
        <thead>
            <tr>
                <th>№</th>
                <th>Todo iteam</th>
                <th>Description</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todo_list %}
            <tr>
                <td>{{ todo.id }}</td>
                <td>{{ todo.title}}</td>
                <td>{{ todo.description}}</td>
                <td>
                    {% if todo.complete == False %}
                        <span>In progress</span>
                    {% else %}
                        <span>Completed</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ url_for('todo.update', todo_id=todo.id) }}">Update</a>
                    <a href="{{ url_for('todo.delete', todo_id=todo.id) }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}