app/post/models.py
from datetime import datetime
from app import db
from sqlalchemy import Enum

post_tag = db.Table('post_tag',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    text = db.Column(db.String)
    image = db.Column(db.String, default='default.png')
    created = db.Column(db.TIMESTAMP, default=datetime.now)
    type = db.Column(Enum('news', 'publication', 'coding', 'other'), default='news')
    enabled = db.Column(db.Boolean, default=True)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    category = db.relationship('Category', backref=db.backref('posts', uselist=False))

    def __repr__(self):
        return f"<Post {self.id}: {self.title}>"

    
class Category(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)

    def __repr__(self):
        return f"<Category {self.id}: {self.name}>"
    
class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)

    def __repr__(self):
        return f"<Tag {self.id}: {self.name}>"

app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed
from wtforms.widgets import CheckboxInput, ListWidget

type_choices = [("news", "News"), ("publication", "Publication"),("coding", "Coding"), ("other", "Other")]
enabled_choices = [(True, "True"), (False, "False")]


class PostForm(FlaskForm):
    title = StringField(
        label="Title", validators=[DataRequired(message="This field is required.")]
    )
    text = TextAreaField(
        label="Write your post here",
        render_kw={"rows": 13, "cols": 11},
        validators=[DataRequired(message="This field is required.")],
    )
    image = FileField(
        "Post Picture",
        validators=[FileAllowed(["jpg", "png"], message="This file is not allowed")],
    )
    type = SelectField(
        "Type",
        choices=type_choices,
        validators=[DataRequired(message="Please select a type.")],
    )
    category = SelectField('Category', validators=[DataRequired(message="This field is required.")])
    submit = SubmitField("Submit")


class EditPostForm(FlaskForm):
    title = StringField(label="Title")
    text = TextAreaField(label="Write your post here", render_kw={"rows": 13, "cols": 11},)
    image = FileField(
        "Post Picture",
        validators=[FileAllowed(["jpg", "png"], message="This file is not allowed")],
    )
    type = SelectField("Type", choices=type_choices)
    enabled = SelectField("Enabled", choices=enabled_choices)
    category = SelectField('Category')
    submit = SubmitField("Submit")
    
class CategoryForm(FlaskForm):
    name = StringField("Category name",
                       validators=[DataRequired(message="This field is required."),])
    submit = SubmitField("Submit")
    
class EditCategoryForm(FlaskForm):
    name = StringField("Category name",
                       validators=[DataRequired(message="This field is required."),])
    submit = SubmitField("Submit")

app/post/__init__.py
from flask import Blueprint

post_blueprint = Blueprint('post', __name__, template_folder="templates/post")

from . import views

app/post/views.py
from flask import flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from .models import Post, Category, Tag
from .forms import PostForm, EditPostForm, CategoryForm, EditCategoryForm
from . import post_blueprint
from .utilities import save_picture
from app import db
from sqlalchemy import desc

@post_blueprint.route('/post/create', methods=['GET', 'POST'])
@login_required
def create():
    form = PostForm()
    
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]

    if form.validate_on_submit():
        category = Category.query.get(form.category.data)
        title = form.title.data
        text = form.text.data
        type = form.type.data
        
        if form.image.data:
            image = save_picture(form.image.data)
        else:
            image = 'default.png'
            
        post = Post(title=title, text=text, image=image, type=type, category=category, user_id=current_user.id)
        try:
            db.session.add(post)
            db.session.commit()
            flash('Your post added successfully', 'success')
        except Exception as e:
            db.session.rollback()
            flash(f'An error occurred: {str(e)}', 'danger')
        return redirect(url_for("post.create"))
                        
    return render_template("create_post.html", form=form)

@post_blueprint.route('/post', methods=['GET'])
def all_posts():
    page = request.args.get('page', 1, type=int)
    posts_per_page = 3

    posts = Post.query.filter_by(enabled=True).order_by(Post.created.desc()).paginate(page=page, per_page=posts_per_page)

    return render_template('all_posts.html', posts=posts)

@post_blueprint.route('/post/<int:post_id>', methods=['GET'])
def view_post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('view_post.html', post=post)

@post_blueprint.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = EditPostForm()
    
    
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]
    print('1')
    if form.validate_on_submit():
        print('2')
        if form.image.data:
            post.image = save_picture(form.image.data)
        try:
            post.title = form.title.data
            post.text = form.text.data
            post.type = form.type.data
            post.enabled = bool(form.enabled.data)
            post.category = Category.query.get(form.category.data)

            db.session.commit()
            flash('Post has been updated!', 'success')
        except Exception as e:
            db.session.rollback()
            flash(f"Failed to update! Error: {str(e)}", category="danger") 

        return redirect(url_for('post.view_post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.text.data = post.text
        form.type.data =  post.type
        form.enabled.data = post.enabled
        form.category.data = post.category_id

    return render_template('edit_post.html', post=post, form=form)


@post_blueprint.route('/post/<int:post_id>/delete', methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    try:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted successfully', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'An error occurred: {str(e)}', 'danger')

    return redirect(url_for('post.all_posts'))




@post_blueprint.route('/categories', methods=['GET', 'POST'])
def categories():
    form = CategoryForm()
    
    if form.validate_on_submit():
        print(form.name.data)
        name = form.name.data
        new_category = Category(name=name)
        try:
            db.session.add(new_category)
            db.session.commit()
            flash('New category added successfully', 'success')
            return redirect(url_for("post.categories"))
        except Exception as e:
            db.session.rollback()
            flash(f'An error occurred: {str(e)}', 'danger')
            
    categories = Category.query.all()

    return render_template('categories.html', form=form, categories=categories)


@post_blueprint.route('/<int:category_id>/edit', methods=['GET', 'POST'])
def edit_category(category_id):
    category = Category.query.get_or_404(category_id)
    form = EditCategoryForm()
    
    if form.validate_on_submit():
        try:
            category.name = form.name.data
            db.session.commit()
            flash('Category has been updated!', 'success')
        except Exception as e:
            db.session.rollback()
            flash(f"Failed to update! Error: {str(e)}", category="danger") 

        return redirect(url_for('post.categories'))

    elif request.method == 'GET':
        form.name.data = category.name

    return render_template('edit_category.html', category=category, form=form)

@post_blueprint.route('/<int:category_id>/delete', methods=['POST'])
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    db.session.delete(category)
    db.session.commit()
    return redirect(url_for('post.categories'))

app/post/templates/post/all_posts.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block title %} Posts{% endblock %}
{% block body %}

<div style="text-align: center; padding-top: 20px;">
    <h1 class="title">
        All posts</h1>
</div>
<div class="table-container">
    <Table responsive>
        <thead>
            <tr>
                <th>Title</th>
                <th>Image</th>
                <th>Text</th>
                <th>Type</th>
                <th>Category</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr>
                <td>
                    <a href="{{ url_for('post.view_post', post_id=post.id) }}">{{ post.title }}</a>
                </td>
                
                <td>
                    <img alt="..." src="{{ url_for('static', filename='post_pics/' + post.image) }}" style="width: 150px; height: 150px;">
                 </td>
                 <td> {{ post.text[:100] }}{% if post.text|length > 100 %}...{% endif %}</td>
                <td> {{post.type}}</td>
                <td> {{ post.category.name }}</td>
                <td> {{post.created.strftime('%Y-%m-%d %H:%M:%S')}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </Table>
    <nav aria-label="...">
        <ul>
            <li class="{% if not posts.has_prev %}disabled{% endif %}">
                <a
                   href="{{ url_for(".all_posts", page=posts.prev_num) }}"
                   tabindex="-1"><</a>
            </li>
    
            {% for page in posts.iter_pages(left_edge=1, left_current=2, right_current=2, right_edge=1) %}
                <li class="{% if page == posts.page %}active{% endif %}">
                    <a  href="{{ url_for(".all_posts", page=page) }}">
                        {{ page or "..." }}
                    </a>
                </li>
            {% endfor %}
    
            <li class="{% if not posts.has_next %}disabled{% endif %}">
                <a href="{{ url_for(".all_posts", page=posts.next_num) }}">></a>
            </li>
        </ul>
    </nav>
    
    
</div>

{% endblock %}

app/post/templates/post/categories.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block title %} Categories{% endblock %}
{% block body %}

<div class="text-center">
    <h2 class="title">Categories</h2>
  </div>

<div class="container">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for category in categories %}
          <tr>
            <td>{{ category.id }}</td>
            <td>{{ category.name }}</td>
            <td style="display: flex; justify-content: center;">
              <a href="{{ url_for('post.edit_category', category_id=category.id) }}" class="btn btn-primary">Edit</a>
              <form action="{{ url_for('post.delete_category', category_id=category.id) }}" method="post" style="display: block; border: none; padding: 0; width: auto; max-width: initial">
                <button type="submit" class="btn btn-danger">Delete</button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
</div>
<div style="text-align: center; padding-top: 20px;">
    <h2 class="title">
        Add new category</h2>
</div>
<div style="max-width: 60%;">
    <div>
        <form method="post" action="{{ url_for('post.categories') }}" novalidate >
            {{ form.csrf_token }}
                {{ render_field(form.name)}}
            {{ form.submit(class="btn-round btn btn-primary btn-lg") }}
        </form>
    </div>
</div>


{% endblock %}

app/post/templates/post/create_post.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block title %} Create Post{% endblock %}
{% block body %}

<div style="text-align: center; padding-top: 20px;">
    <h2 class="title">
        Here you can add your post</h2>
</div>
<div style="max-width: 60%;">
    <div>
        <form method="post" action="{{ url_for('post.create') }}" novalidate enctype="multipart/form-data">
            {{ form.csrf_token }}
                {{ render_field(form.title)}}
                {{ render_field(form.text)}}
                {{ render_field(form.type)}}
                {{ render_field(form.category)}}
                <div>
                    <label>Image</label>
                    <div>
                        <label for="picture" id="custom-file-label">{{ form.image.label }}</label>
                        {{ render_field(form.image, show_label=false, show_errors=false, id='picture') }}
    
                        {% if form.image.errors %}
                        <br><br>
                            <ul class="errors">
                                {% for error in form.image.errors %}
                                    <p class="danger">{{ error }}</p>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                </div>
            {{ form.submit(class="btn-round btn btn-primary btn-lg") }}
        </form>
    </div>
</div>



{% endblock %}

app/post/templates/post/edit_category.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block title %} Edit category{% endblock %}
{% block body %}


<div style="text-align: center; padding-top: 20px;">
    <h2>
        Edit category</h2>
</div>
<div style="max-width: 60%;">
    <div>
        <form method="post" action="{{ url_for('post.edit_category', category_id=category.id) }}" novalidate style="display: block; border: none; padding: 0; width: auto; max-width: initial">
            {{ form.csrf_token }}
            {{ render_field(form.name) }}
            {{ form.submit(class="btn-round btn btn-primary btn-lg") }}
        </form>        
    </div>
</div>


{% endblock %}

app/post/templates/post/edit_post.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}
{% block title %} Edit post{% endblock %}

{% block body %}

<div id="edit_post_section" style="text-align: center;">
    <h1 class="title">Edit post</h1>
</div>

<div style="max-width: 60%;">
    <div>
        <form method="post" action="{{ url_for('post.edit_post', post_id=post.id) }}" novalidate enctype="multipart/form-data">
            {{ form.csrf_token }}
                {{ render_field(form.title)}}
                {{ render_field(form.text)}}
                {{ render_field(form.type)}}
                {{ render_field(form.enabled)}}
                {{ render_field(form.category)}}
                <div>
                    <label for="picture">Image</label>
                    <div>
                        <label for="picture" id="custom-file-label">{{ form.image.label }}</label>
                        {{ render_field(form.image, show_label=false, show_errors=false, id='picture') }}
    
                        {% if form.image.errors %}
                        <br><br>
                            <ul class="errors">
                                {% for error in form.image.errors %}
                                    <p class="danger">{{ error }}</p>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                </div>
            {{ form.submit(class="btn-round btn btn-primary btn-lg") }}
        </form>
    </div>
</div>

{% endblock %}

app/post/templates/post/view_post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block body %}
<div style="text-align: center; padding-top: 20px;">
    <h1>{{ post.title }}</h1>
</div>
<div style="padding-top: 50px;">
    <div >
        <div>
            <div>
                <p><strong>Image:</strong></p>
                <img alt="Post Image" src="{{ url_for('static', filename='post_pics/' + post.image) }}" style="width: 300px; height: 300px;">
            </div>
        </div>
        <div>
            <div>
                <p><strong>Text:</strong> {{ post.text }}</p>
            </div>
        </div>
        <div>
            <div>
                <p><strong>Type:</strong> {{ post.type }}</p>
                <p><strong>Category:</strong> {{ post.category.name }}</p>
                </p>
                <p><strong>Date:</strong> {{ post.created.strftime('%Y-%m-%d %H:%M:%S') }}</p>
                <p><strong>Enabled:</strong> {{ post.enabled }}</p>

                {% if current_user.is_authenticated and post.user_id == current_user.id %}
                <div class="mt-4">
                    <a href="{{ url_for('post.edit_post', post_id=post.id) }}">Edit</a>
                    <form action="{{ url_for('post.delete_post', post_id=post.id) }}" method="post" class="d-inline" onsubmit="return confirm('Do you want to delete the post?');" style="display: block; border: none; padding: 0; width: auto; max-width: in<button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}